import Head from "next/head";
import Image from 'next/image';
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useCallback, useState } from "react";
import { ethers, Signer } from "ethers";
import MyNFT from "../artifacts/contracts/MyNFT.sol/MyNFT.json";
import contract from "../address.json";
import { message, Button, notification,Space } from "antd";


const inter = Inter({ subsets: ["latin"] });


export default function Home() {
  const [signer, setSigner] = useState<Signer | null>(null);
  const [tokenId, setTokenId] = useState(null);
  const [path,setPath] = useState('/justice_league.jpg');
  const [sheep_blood,setSheepBlood] = useState(0);
  const [sheep_power,setSheepPower] = useState(0);
  const [wolf_blood,setWolfBlood] = useState(0);
  const [wolf_power,setWolfPower] = useState(0);
  const connectWallet = useCallback(async () => {
    const provider = new ethers.providers.Web3Provider(window.ethereum);
    await provider.send("eth_requestAccounts", []);
    const signer = provider.getSigner();
    if (signer) {
      message.success("连接钱包成功");
      setSigner(signer);
    }
    return 'hello';
  }, []);

  const callContract = useCallback(async (key) => {
    if (!signer) {
      message.error("请先连接钱包");
      return;
    }
    const myNFT = new ethers.Contract(contract.address, MyNFT.abi, signer);
    const transaction = await myNFT.safeMint(
      await signer.getAddress(),
       key,
      { value: 10 ** 10 }
    );
    const txReceipt = await transaction.wait();
    const id =await myNFT.last();
    console.log('id:',id);
    setTokenId (id.tokenId);
    setSheepBlood(id.status.sheep_blood);
    setSheepPower(id.status.sheep_attack_power);
    setWolfBlood(id.status.wolf_blood);
    setWolfPower(id.status.wolf_attack_power);
    notification.success({
      message: "mint NFT",
      description: (
        <div>
          <p>current tokenId: {id.tokenId.toString()}</p>
        </div>

      ),
    });
    if (key === 0) {
      setPath( '/lucky_sheep.jpg');
    } else if (key === 1 ) {
      setPath( '/lazy_sheep.jpg');
    } else if (key === 2) {
      setPath( '/beauty_sheep.jpg');
    } 
  }, [signer,tokenId]);

  const attack = useCallback(async () => {
    if (!signer) {
      message.error("请先连接钱包");
      return;
    }
    const myNFT = new ethers.Contract(contract.address, MyNFT.abi, signer);
    const transaction = await myNFT.attack(tokenId);
    await transaction.wait();
    const id =await myNFT.last();
    var info = "after attack,war is continue...";
    if (id.status.sheep_blood === 0) {
      info = "Game over,winner: Wolf";
    } else if (id.status.wolf_blood === 0) {
      info = "Game over,winner: Sheep";
    }else {
      info = "Game is processing...";
    }
    setSheepBlood(id.status.sheep_blood);
    setWolfBlood(id.status.wolf_blood);

  },[signer,tokenId]);
 
  return (
    
    <>
      <Head>
        <title>Hero Honor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Space>
        <Button type={"primary"} onClick={connectWallet}>
          connect wallet
        </Button>
        <Button type={"primary"} onClick={() =>{callContract(0)}}>
          mint lucky boy
        </Button>
        <Button type={"primary"} onClick={() =>{callContract(1)}}>
          mint lazy boy
        </Button>
        <Button type={"primary"} onClick={() =>{callContract(2)}}>
          mint beauty girl
        </Button>
        <Button type={"primary"} onClick={attack}>
          attack
        </Button>
        </Space>
        <Space>
          <div>
          <li>blood ： {sheep_blood}</li>
          <li>power ： {sheep_power}</li>
        <Image src= {path} height={500} 
    width={500} alt="jpg" />
      <h2>{sheep_blood !== 0 && wolf_blood === 0 ? 'WINNER':''}</h2>
    </div>
    <div>
      <h1>  VS   </h1>
      </div>
      <div>
      <li>blood ： {wolf_blood}</li>
      <li>power ： {wolf_power}</li>
      <Image src="/wolf.jpg" height={500} 
    width={500} alt="jpg" />
     <h2>{sheep_blood === 0 && wolf_blood !== 0 ? 'WINNER':''}</h2>
    </div>
        </Space>
      </main>
    </>
  );
}
